version: "3"
services:
  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    ports:
      - 9200:9200
    environment:
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"  #set heap memory here
      discovery.type: single-node
      ELASTIC_PASSWORD: PleaseChangeMe@1!
      KEYSTORE_PASSWORD: PleaseChangeMe@1!
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    restart: always
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:7.13.0
    ports:
      - 5601:5601
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml

volumes:
  elasticsearchdata:
